server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/config_management?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: true
      encoding: UTF-8
  transaction:
    rollback-on-commit-failure: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.model
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html 

config:
  version:
    max-datasource-versions: 5
    max-apirecord-versions: 5
    max-api-meta-versions: 5
diff:
  ignore-fields:

logging:
  level:
    com.example.mapper: DEBUG
    org.springframework.jdbc.core: TRACE